In [2]:
import pandas as pd

path_requests = "tripdata_ids_2011-02-01_000000_2011-02-07_235959.csv"
folder = "C:/Users/LocalAdmin/OneDrive/leap_forward/street_network_server/tenv/data/out/manhattan/tripdata/ids/"

df = pd.read_csv(folder + path_requests, parse_dates=True)

In [9]:
earliest = "2011-02-01 18:00:00"
cut_df =df[df["pickup_datetime"]>=earliest]
cut_df.head(20)

,pickup_datetime,passenger_count,pk_id,dp_id,pickup_longitude,pickup_latitude,dropoff_longitude,dropoff_latitude,fare_amount,payment_type,total_amount,tip_amount,trip_distance
150970,2011-02-01 18:00:00,1,2016,943,-73.962300,40.779115,-73.970610,40.798705,8.9,CRD,11.65,1.25,2.32
150971,2011-02-01 18:00:00,2,4024,2363,-73.996907,40.725485,-73.986368,40.730920,6.1,CSH,7.60,NaN,1.31
150972,2011-02-01 18:00:00,1,1325,1132,-73.985700,40.727032,-73.959730,40.798428,18.5,CRD,22.50,2.50,6.19
150973,2011-02-01 18:00:00,1,2105,1575,-73.985840,40.757387,-74.010405,40.717795,10.9,CRD,14.00,1.60,3.34
150974,2011-02-01 18:00:00,1,3158,3155,-74.010002,40.712452,-74.004782,40.718958,3.7,CRD,6.00,0.80,0.52
150975,2011-02-01 18:00:00,6,2647,1832,-73.981120,40.751077,-73.991103,40.750898,7.3,CRD,10.40,1.60,1.08
150976,2011-02-01 18:00:00,1,2818,521,-73.954948,40.780058,-73.982425,40.776918,10.1,CRD,13.60,2.00,2.29
150977,2011-02-01 18:00:00,1,2692,2665,-73.975245,40.757570,-73.948197,40.777847,9.3,CSH,10.80,NaN,2.71
150978,2011-02-01 18:00:00,1,2980,3016,-73.976657,40.748373,-73.975253,40.761210,8.1,CSH,9.60,NaN,1.21
150979,2011-02-01 18:00:00,5,792,331,-74.000070,40.733030,-74.005622,40.745693,7.3,CSH,8.80,NaN,1.29
150980,2011-02-01 18:00:00,1,3840,2449,-73.981817,40.778153,-73.967975,40.793012,7.3,CSH,8.80,NaN,1.55
150981,2011-02-01 18:00:00,5,527,2488,-73.980770,40.782607,-73.978760,40.752342,10.5,CSH,12.00,NaN,2.61
150982,2011-02-01 18:00:00,1,2937,2045,-74.007142,40.743603,-73.959847,40.770800,13.3,CRD,16.80,2.00,4.14
150983,2011-02-01 18:00:00,1,1948,3766,-73.961703,40.771072,-73.966777,40.767223,4.1,CSH,5.60,NaN,0.47
150984,2011-02-01 18:00:00,2,492,793,-74.000798,40.720603,-73.999635,40.733453,4.9,CSH,6.40,NaN,1.21
150985,2011-02-01 18:00:00,5,2621,1738,-73.996488,40.723850,-73.990378,40.733713,4.5,CSH,6.00,NaN,0.80
150986,2011-02-01 18:00:00,5,3870,3787,-73.981792,40.779195,-73.959670,40.777575,8.9,CSH,10.40,NaN,2.42
150987,2011-02-01 18:00:00,5,396,4441,-73.954763,40.765542,-73.971288,40.745342,6.1,CSH,7.60,NaN,1.76
150988,2011-02-01 18:00:00,1,804,1933,-73.992732,40.742722,-73.999322,40.749412,4.9,CRD,8.40,2.00,0.88
150989,2011-02-01 18:00:00,1,3612,4283,-73.979917,40.749178,-73.990997,40.750697,6.1,CSH,7.60,NaN,0.93